export const LOAD_PILOTS_SUCCESS = "LOAD_PILOTS_SUCCESS";
export const LOAD_INSTITUTIONS_SUCCESS = "LOAD_INSTITUTIONS_SUCCESS";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const FILTER_SUCCESS = "FILTER_SUCCESS";
